theme: jekyll-theme-slate
title: CDW Genomics Projects
description: Updates, info, and supplementary material for my projects

# Optional
permalink: /:title/

# Fix the webpages being confined to 1/3 of the screen
include:
  - cdwgen.github.io/assets/css/custom.css
