remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

title: CDW Genomics Projects
description: Updates, info, and supplementary material for my projects

# Optional permalink style
permalink: /:title/

# Optional custom CSS (for full-width iframes)
include:
  - assets/css/custom.css
